### ISSUE TITLE
Poor performance with lots of sites

### ISSUE THREAD

**Issue by mholt** [mastercactapus/caddy-proxyprotocol#3]
Hi there! I'm writing in because we know of a Caddy instance that has several thousand (tens of thousands) of sites configured to use the proxyprotocol plugin.

It appears that [this double for loop](https://github.com/mastercactapus/caddy-proxyprotocol/blob/5af98340cafa2a5010e1b8fa3b6d1bd69b3b59e0/listeners.go#L35-L36) is causing unacceptably high latency during new connections, because it must iterate up to tens of thousands of sites before finding the right one, and then through each subnet (in this case, 2 per site).

Do you have any ideas about how to improve performance here? Is it possible to replace the slice with a map, or do a binary search?

**Comment by mastercactapus** [comment]
It looks like the main issue is that the listener middleware is being applied once per site, instead of once per socket/port. The subsequent middleware instances are waiting (default is no timeout) for the PROXY header. If there are 10k middlewares, one would need to send 10k PROXY headers, unless using a specific subnet filter with the current code.

The `parse-test` branch is working performance wise by removing the duplication all around. I tried 15k sites without issue, though there's still a little to do to fix reload.

**Comment by mholt** [comment]
Ah, that explanation does make sense.

This looks great!! I'm going to get in touch with the affected user and see how it goes.

Thank you so much for your time to look into this. I will get back to you ASAP on this. In the meantime, if there's anything I can do to make using Caddy better/easier, don't hesitate to ask. :)
