### ISSUE TITLE
Caddy 2 is ready for a PROXY protocol module

### ISSUE THREAD

**Issue by mholt** [mastercactapus/caddy-proxyprotocol#9]
Hi!

Whenever you're ready, Caddy 2 (still in beta, at time of writing) is now able to accommodate wrapping listeners. The commit that adds this is https://github.com/caddyserver/caddy/commit/f596fd77bb6880485d2bfc6b18a775b5572da260.

The docs aren't published yet, but basically, [the servers struct in Caddy's JSON](https://caddyserver.com/docs/json/apps/http/servers/) will have a new field called `listener_wrappers` which takes an array of structs. Each struct can configure a different listener wrapper. (Users can even specify which wrappers come before or after the TLS listener, so if a plugin needs to read before the TLS handshake, that's fine too! But by default they go after TLS.)

Listener wrapper modules are in the `caddy.listeners` namespace, so for example: `caddy.listeners.proxy_protocol` might be your module's ID.

The site [has docs for extending Caddy 2](https://caddyserver.com/docs/extending-caddy) but I will be happy to help answer any questions you have in the process!

**Comment by unixfox** [comment]
@mholt Wouldn't it better to have it directly into Caddy v2 core? I feel like it's an essential feature, even [NGINX has it built-in](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/), here is why:

On Kubernetes, most of the deployments of web servers are behind a TCP load balancer and with PROXY protocol enabled in order to pass the client IP address.
Due to the lack of PROXY protocol support the whole [Caddy 2 ingress controller](https://github.com/caddyserver/ingress) project can't be used properly in production because it would mean losing the original client IP address.

Currently, the only hack in order to use it in production is to turn off the automatic TLS feature of Caddy 2 and deploy Caddy 2 behind an HTTP load balancer in order to preserve the original client IP address.

**Comment by mholt** [comment]
@unixfox 

> Wouldn't it better to have it directly into Caddy v2 core?

No, because the only thing the Caddy core does is load and run configuration. It has no knowledge of any protocols, not even HTTP or TLS, let alone the PROXY protocol. Here is an overview of its architecture: https://caddyserver.com/docs/architecture

Everything is a plugin/module.

**Comment by unixfox** [comment]
Sorry when I meant in the core of Caddy v2, it's as an officially supported module in the Caddy repository just like the others modules like `caddyhttp`, `caddytls` and more.

**Comment by mholt** [comment]
Maybe someday, if it is popular enough, but we've already bitten off more than we can chew.

First, it just needs to be written.

**Comment by francislavoie** [comment]
@mastercactapus I'm just wondering if you have any interest in porting this to Caddy v2? There has been some interest shown for having this feature supported in v2 and I'm sure users would appreciate it 😄

**Comment by digitalmio** [comment]
Thinking out loud - is there any alternative? Can I go back to Caddy v1? Looks like on Kubernetes it's the only way? All providers are using Load Balancers that do require use of PROXY. Thanks.

**Comment by mastercactapus** [comment]
Anyone able to test, it would be much appreciated: https://github.com/mastercactapus/caddy2-proxyprotocol

@mholt if you have a chance, let me know how it looks. I was able to get it working locally, still needs README & any publishing that needs to happen but it's a start.

**Comment by francislavoie** [comment]
@mastercactapus you can see the list of available plugins here: https://caddyserver.com/download you just need to sign up for an account (top nav) and register your plugin there

**Comment by mholt** [comment]
@mastercactapus You are the hero we need, not the hero we deserve. :clap:

Looks great! A couple minor points of feedback:

https://github.com/mastercactapus/caddy2-proxyprotocol/blob/13351f896fe8bd8e34a4e738bbed6d4051049a68/caddy.go#L18

In Caddy 2 it's conventional to use `_` for long names, so `caddy.listeners.proxy_protocol` would look better IMO.

https://github.com/mastercactapus/caddy2-proxyprotocol/blob/13351f896fe8bd8e34a4e738bbed6d4051049a68/proxyprotocolsupport.go#L13

Use `caddy.Duration` instead of `string` for duration fields. It'll be parsed automatically for you.

https://github.com/mastercactapus/caddy2-proxyprotocol/blob/13351f896fe8bd8e34a4e738bbed6d4051049a68/proxyprotocolsupport.go#L46-L49

Can probably get rid of the `Validate()` method; doesn't really do anything useful (provision does the same thing).

The package name `caddy2proxyprotocol` seems a bit redundant, but I can understand why you called it that. It's fine, I was just thinking it could replace the one in this repo.

Also the type name `ProxyProtocolSupport` seems a bit redundant too, especially paired with the package name: `caddy2proxyprotocol.ProxyProtocolSupport` -- nothing wrong with it per-se, but I wonder if something like `proxyprotocol.Wrapper` might look more like conventional Go. :)

That's all!

We can look into adding Caddyfile support too, should be pretty easy but I think I need to add some code into the Caddyfile adapter that can take listener wrappers out of the "pile" and put them into the final config.

**Comment by mholt** [comment]
PS. If you already had a Caddy account, you still have it, and you can log in with your existing account to register your module. :+1:

**Comment by mastercactapus** [comment]
Made those changes, and published what I have as v0.0.1

Tracking Caddyfile support here: https://github.com/mastercactapus/caddy2-proxyprotocol/issues/1

One thing with the listener wrapper & Caddyfile support (I haven't looked into the adapter stuff) will be ordering, since the PROXY header needs to be the very first frame/packet of the connection, this wrapper will need to be registered first, at least compared to anything protocol related like `tls`.

**Comment by mholt** [comment]
Good to know, thanks! Yeah I'll have to think about the ordering... I'm sure we can come up with something.

**Comment by debtcollapse** [comment]
Wanted to check in on the status of this issue. I'm working on a project that requires both the L4 and Proxy Protocol plugins, so this would be great to see.

I need to accept TCP traffic from an NLB, using Proxy Protocol in order to preserve the source IP and then forward traffic upstream over HTTP.

**Comment by francislavoie** [comment]
@debtcollapse this repo is outdated, the Caddy v2 version is here: https://github.com/mastercactapus/caddy2-proxyprotocol, as mentioned above
